name: twitter_clone
description: A Twin of Great Twitter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  appwrite: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  injectable: ^1.5.4
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  objectbox_generator: ^2.0.0
  connectivity_plus: ^3.0.4
  intl: ^0.17.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  sprintf: ^7.0.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  timeago: ^3.3.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
