// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/auth/auth_db/auth_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 550892018923285746),
      name: 'AuthEntity',
      lastPropertyId: const IdUid(6, 2003006420456647654),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 9191032082832110200),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1341056318338300308),
            name: 'userId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2289220095924422714),
            name: 'sessionId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1939395042222711481),
            name: 'expireAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 609431760789971551),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2003006420456647654),
            name: 'isEmailVerified',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 550892018923285746),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    AuthEntity: EntityDefinition<AuthEntity>(
        model: _entities[0],
        toOneRelations: (AuthEntity object) => [],
        toManyRelations: (AuthEntity object) => {},
        getId: (AuthEntity object) => object.id,
        setId: (AuthEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AuthEntity object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final sessionIdOffset = fbb.writeString(object.sessionId);
          final emailOffset = fbb.writeString(object.email);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, sessionIdOffset);
          fbb.addInt64(3, object.expireAt.millisecondsSinceEpoch);
          fbb.addOffset(4, emailOffset);
          fbb.addBool(5, object.isEmailVerified);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AuthEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              userId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              sessionId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              expireAt: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''),
              isEmailVerified: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 14, false));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [AuthEntity] entity fields to define ObjectBox queries.
class AuthEntity_ {
  /// see [AuthEntity.id]
  static final id =
      QueryIntegerProperty<AuthEntity>(_entities[0].properties[0]);

  /// see [AuthEntity.userId]
  static final userId =
      QueryStringProperty<AuthEntity>(_entities[0].properties[1]);

  /// see [AuthEntity.sessionId]
  static final sessionId =
      QueryStringProperty<AuthEntity>(_entities[0].properties[2]);

  /// see [AuthEntity.expireAt]
  static final expireAt =
      QueryIntegerProperty<AuthEntity>(_entities[0].properties[3]);

  /// see [AuthEntity.email]
  static final email =
      QueryStringProperty<AuthEntity>(_entities[0].properties[4]);

  /// see [AuthEntity.isEmailVerified]
  static final isEmailVerified =
      QueryBooleanProperty<AuthEntity>(_entities[0].properties[5]);
}
